name: Basic Checkout Lab

on:
    push:
        branches:
            - main
jobs:
    basic-checkout:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository 
              uses: actions/checkout@v4
            
            - name: list files 
              run : ls -la 
            
            - name: Show system info
              run: | 
                  echo "Repository: $GITHUB_REPOSITORY"
                  echo "Operating System: $(uname -a)"
                  echo "Current Directory: $(pwd)"
            
            - name: Check versions
              run: | 
                  echo "Node version: $(node --version)"
                  echo "Python version: $(python --version)"
                  echo "Git version: $(git --version)" 
